service: notifications
frameworkVersion: '3.17.0'

params: ${file(./environment/params.yml)}

provider: ${file(./environment/provider.yml)}

plugins:
    - serverless-plugin-typescript
    - serverless-offline
    - serverless-prune-plugin

custom:
    serverless-offline:
        host: 0.0.0.0
        httpPort: 3008
    cors: ${file(./environment/cors.yml)}
    prune:
        automatic: true
        number: 3

package:
    individually: true
    exclude:
        - '.*/**'
        - 'node_modules'

functions:
  notifications-create:
    description: Create a new notification
    handler: bin/notifications-create
    events:
      - http:
          path: /notifications
          method: post
          cors: true
          private: true
      - sns:
          arn: ${env:SNS_CHECKOUT_COMPLETE_ARN}
          topicName: ${env:SNS_CHECKOUT_COMPLETE_TOPIC}
    package:
      include:
        - ./bin/notifications-create
    tags:
        env: ${env:ENVIRONMENT}
        service: notifications          
  notifications-getall:
    description:  Get all the products notifications  
    handler: bin/notifications-create
    events:
      - http:
          path: /notifications
          method: get
          cors: true
          private: true
    package:
      include:
        - ./bin/enrollment-products-getall
    tags:
        env: ${env:ENVIRONMENT}
        service: notifications